<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleAlphaDate,
    type TemporalNumericStyleScaleOptions,
  } from "@ggts-sh/spec";
  import "@ggts-sh/core/temporal";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: TemporalNumericStyleScaleOptions = $props();
  createPlotLayer("scale", () => scaleAlphaDate(definedProps(props)));
</script>
