<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleColorSteps, type StepsScaleOptions } from "@ggts-sh/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: StepsScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorSteps(definedProps(props)));
</script>
