<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleFillManual, type ManualColorScaleOptions } from "@ggts-sh/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ManualColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillManual(definedProps(props)));
</script>
