<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleXContinuous,
    type ContinuousPositionScaleOptions,
  } from "@ggts-sh/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: ContinuousPositionScaleOptions = $props();
  createPlotLayer("scale", () => scaleXContinuous(definedProps(props)));
</script>
