<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleSizeArea, type SizeAreaScaleOptions } from "@ggts-sh/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: SizeAreaScaleOptions = $props();
  createPlotLayer("scale", () => scaleSizeArea(definedProps(props)));
</script>
