<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import {
    scaleColorDiscrete,
    type DiscreteColorScaleOptions,
  } from "@ggts-sh/spec";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: DiscreteColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleColorDiscrete(definedProps(props)));
</script>
