<!-- GENERATED by scripts/gen-scale-children.ts — do not edit. Run: bun run scale:children:gen -->
<script lang="ts">
  import { scaleFillDate, type TemporalColorScaleOptions } from "@ggts-sh/spec";
  import "@ggts-sh/core/temporal";
  import {
    createPlotLayer,
    definedProps,
  } from "../layers/plot-layer.svelte.js";

  const props: TemporalColorScaleOptions = $props();
  createPlotLayer("scale", () => scaleFillDate(definedProps(props)));
</script>
