/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import "@ggsvelte/core/temporal";
import type { ReactNode } from "react";
import type {
  BinnedColorScaleOptions,
  BinnedFiniteStyleScaleOptions,
  ColorBrewerScaleOptions,
  ColorDistillerScaleOptions,
  ColorFermenterScaleOptions,
  ContinuousPositionScaleOptions,
  DiscreteColorScaleOptions,
  DiscreteFiniteStyleScaleOptions,
  DiscreteNumericStyleScaleOptions,
  DiscretePositionScaleOptions,
  Gradient2ScaleOptions,
  GradientScaleOptions,
  GradientnScaleOptions,
  GreyScaleOptions,
  HueScaleOptions,
  IdentityColorScaleOptions,
  IdentityFiniteStyleScaleOptions,
  IdentityNumericStyleScaleOptions,
  LinetypeName,
  ManualColorScaleOptions,
  ManualFiniteStyleScaleOptions,
  ManualNumericStyleScaleOptions,
  OrdinalColorScaleOptions,
  PointShapeName,
  SequentialColorScaleOptions,
  SequentialStyleScaleOptions,
  SizeAreaScaleOptions,
  Steps2ScaleOptions,
  StepsScaleOptions,
  StepsnScaleOptions,
  TemporalColorScaleOptions,
  TemporalNumericStyleScaleOptions,
  TemporalScaleOptions,
  TransformedColorScaleOptions,
  TransformedPositionScaleOptions,
  ViridisScaleOptions,
} from "@ggsvelte/spec";
import {
  scaleXContinuous,
  scaleYContinuous,
  scaleXLog10,
  scaleYLog10,
  scaleXSqrt,
  scaleYSqrt,
  scaleXReverse,
  scaleYReverse,
  scaleXBinned,
  scaleYBinned,
  scaleXDate,
  scaleXDatetime,
  scaleXTime,
  scaleYDate,
  scaleYDatetime,
  scaleYTime,
  scaleXMonthDay,
  scaleYMonthDay,
  scaleXDiscrete,
  scaleYDiscrete,
  scaleColorContinuous,
  scaleColorDiscrete,
  scaleColorBinned,
  scaleColorBrewer,
  scaleColorDistiller,
  scaleColorFermenter,
  scaleColorSteps,
  scaleColorSteps2,
  scaleColorStepsn,
  scaleColorGradient,
  scaleColorGradient2,
  scaleColorGradientn,
  scaleColorHue,
  scaleColorGrey,
  scaleColorOrdinal,
  scaleColorLog10,
  scaleColorSqrt,
  scaleColorDate,
  scaleColorDatetime,
  scaleColorManual,
  scaleColorIdentity,
  scaleFillContinuous,
  scaleFillDiscrete,
  scaleFillBinned,
  scaleFillSteps,
  scaleFillSteps2,
  scaleFillStepsn,
  scaleFillGradient,
  scaleFillGradient2,
  scaleFillGradientn,
  scaleFillHue,
  scaleFillGrey,
  scaleFillOrdinal,
  scaleFillLog10,
  scaleFillSqrt,
  scaleFillDate,
  scaleFillDatetime,
  scaleFillManual,
  scaleFillIdentity,
  scaleFillBrewer,
  scaleFillDistiller,
  scaleFillFermenter,
  scaleColorViridisC,
  scaleColorViridisD,
  scaleColorViridisB,
  scaleFillViridisC,
  scaleFillViridisD,
  scaleFillViridisB,
  scaleSizeContinuous,
  scaleSizeDiscrete,
  scaleSizeBinned,
  scaleSizeDate,
  scaleSizeDatetime,
  scaleSizeManual,
  scaleSizeIdentity,
  scaleLinewidthContinuous,
  scaleLinewidthDiscrete,
  scaleLinewidthBinned,
  scaleLinewidthDate,
  scaleLinewidthDatetime,
  scaleLinewidthManual,
  scaleLinewidthIdentity,
  scaleAlphaContinuous,
  scaleAlphaDiscrete,
  scaleAlphaBinned,
  scaleAlphaDate,
  scaleAlphaDatetime,
  scaleAlphaManual,
  scaleAlphaIdentity,
  scaleSizeArea,
  scaleSizeBinnedArea,
  scaleRadius,
  scaleShapeDiscrete,
  scaleShapeBinned,
  scaleShapeManual,
  scaleShapeIdentity,
  scaleLinetypeDiscrete,
  scaleLinetypeBinned,
  scaleLinetypeManual,
  scaleLinetypeIdentity,
} from "@ggsvelte/spec";
import { definedProps } from "./defined-props.js";
import { usePlotLayerValue } from "./geom-factory.js";

export function ScaleXContinuous(props: ContinuousPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXContinuous(definedProps(props)));
  return null;
}

export function ScaleYContinuous(props: ContinuousPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYContinuous(definedProps(props)));
  return null;
}

export function ScaleXLog10(props: TransformedPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXLog10(definedProps(props)));
  return null;
}

export function ScaleYLog10(props: TransformedPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYLog10(definedProps(props)));
  return null;
}

export function ScaleXSqrt(props: TransformedPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXSqrt(definedProps(props)));
  return null;
}

export function ScaleYSqrt(props: TransformedPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYSqrt(definedProps(props)));
  return null;
}

export function ScaleXReverse(
  props: Omit<ContinuousPositionScaleOptions, "transform" | "reverse">,
): ReactNode {
  usePlotLayerValue("scale", () => scaleXReverse(definedProps(props)));
  return null;
}

export function ScaleYReverse(
  props: Omit<ContinuousPositionScaleOptions, "transform" | "reverse">,
): ReactNode {
  usePlotLayerValue("scale", () => scaleYReverse(definedProps(props)));
  return null;
}

export function ScaleXBinned(props: ContinuousPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXBinned(definedProps(props)));
  return null;
}

export function ScaleYBinned(props: ContinuousPositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYBinned(definedProps(props)));
  return null;
}

export function ScaleXDate(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXDate(definedProps(props)));
  return null;
}

export function ScaleXDatetime(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXDatetime(definedProps(props)));
  return null;
}

export function ScaleXTime(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXTime(definedProps(props)));
  return null;
}

export function ScaleYDate(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYDate(definedProps(props)));
  return null;
}

export function ScaleYDatetime(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYDatetime(definedProps(props)));
  return null;
}

export function ScaleYTime(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYTime(definedProps(props)));
  return null;
}

export function ScaleXMonthDay(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXMonthDay(definedProps(props)));
  return null;
}

export function ScaleYMonthDay(props: TemporalScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYMonthDay(definedProps(props)));
  return null;
}

export function ScaleXDiscrete(props: DiscretePositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleXDiscrete(definedProps(props)));
  return null;
}

export function ScaleYDiscrete(props: DiscretePositionScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleYDiscrete(definedProps(props)));
  return null;
}

export function ScaleColorContinuous(props: SequentialColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorContinuous(definedProps(props)));
  return null;
}
export { ScaleColorContinuous as ScaleColourContinuous };

export function ScaleColorDiscrete(props: DiscreteColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDiscrete(definedProps(props)));
  return null;
}
export { ScaleColorDiscrete as ScaleColourDiscrete };

export function ScaleColorBinned(props: BinnedColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorBinned(definedProps(props)));
  return null;
}
export { ScaleColorBinned as ScaleColourBinned };

export function ScaleColorBrewer(props: ColorBrewerScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorBrewer(definedProps(props)));
  return null;
}
export { ScaleColorBrewer as ScaleColourBrewer };

export function ScaleColorDistiller(props: ColorDistillerScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDistiller(definedProps(props)));
  return null;
}
export { ScaleColorDistiller as ScaleColourDistiller };

export function ScaleColorFermenter(props: ColorFermenterScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorFermenter(definedProps(props)));
  return null;
}
export { ScaleColorFermenter as ScaleColourFermenter };

export function ScaleColorSteps(props: StepsScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorSteps(definedProps(props)));
  return null;
}
export { ScaleColorSteps as ScaleColourSteps };

export function ScaleColorSteps2(props: Steps2ScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorSteps2(definedProps(props)));
  return null;
}
export { ScaleColorSteps2 as ScaleColourSteps2 };

export function ScaleColorStepsn(props: StepsnScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorStepsn(definedProps(props)));
  return null;
}
export { ScaleColorStepsn as ScaleColourStepsn };

export function ScaleColorGradient(props: GradientScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGradient(definedProps(props)));
  return null;
}
export { ScaleColorGradient as ScaleColourGradient };

export function ScaleColorGradient2(props: Gradient2ScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGradient2(definedProps(props)));
  return null;
}
export { ScaleColorGradient2 as ScaleColourGradient2 };

export function ScaleColorGradientn(props: GradientnScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGradientn(definedProps(props)));
  return null;
}
export { ScaleColorGradientn as ScaleColourGradientn };

export function ScaleColorHue(props: HueScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorHue(definedProps(props)));
  return null;
}
export { ScaleColorHue as ScaleColourHue };

export function ScaleColorGrey(props: GreyScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorGrey(definedProps(props)));
  return null;
}
export { ScaleColorGrey as ScaleColourGrey };

export function ScaleColorOrdinal(props: OrdinalColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorOrdinal(definedProps(props)));
  return null;
}
export { ScaleColorOrdinal as ScaleColourOrdinal };

export function ScaleColorLog10(props: TransformedColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorLog10(definedProps(props)));
  return null;
}
export { ScaleColorLog10 as ScaleColourLog10 };

export function ScaleColorSqrt(props: TransformedColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorSqrt(definedProps(props)));
  return null;
}
export { ScaleColorSqrt as ScaleColourSqrt };

export function ScaleColorDate(props: TemporalColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDate(definedProps(props)));
  return null;
}
export { ScaleColorDate as ScaleColourDate };

export function ScaleColorDatetime(props: TemporalColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorDatetime(definedProps(props)));
  return null;
}
export { ScaleColorDatetime as ScaleColourDatetime };

export function ScaleColorManual(props: ManualColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorManual(definedProps(props)));
  return null;
}
export { ScaleColorManual as ScaleColourManual };

export function ScaleColorIdentity(props: IdentityColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorIdentity(definedProps(props)));
  return null;
}
export { ScaleColorIdentity as ScaleColourIdentity };

export function ScaleFillContinuous(props: SequentialColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillContinuous(definedProps(props)));
  return null;
}

export function ScaleFillDiscrete(props: DiscreteColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDiscrete(definedProps(props)));
  return null;
}

export function ScaleFillBinned(props: BinnedColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillBinned(definedProps(props)));
  return null;
}

export function ScaleFillSteps(props: StepsScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillSteps(definedProps(props)));
  return null;
}

export function ScaleFillSteps2(props: Steps2ScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillSteps2(definedProps(props)));
  return null;
}

export function ScaleFillStepsn(props: StepsnScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillStepsn(definedProps(props)));
  return null;
}

export function ScaleFillGradient(props: GradientScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGradient(definedProps(props)));
  return null;
}

export function ScaleFillGradient2(props: Gradient2ScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGradient2(definedProps(props)));
  return null;
}

export function ScaleFillGradientn(props: GradientnScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGradientn(definedProps(props)));
  return null;
}

export function ScaleFillHue(props: HueScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillHue(definedProps(props)));
  return null;
}

export function ScaleFillGrey(props: GreyScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillGrey(definedProps(props)));
  return null;
}

export function ScaleFillOrdinal(props: OrdinalColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillOrdinal(definedProps(props)));
  return null;
}

export function ScaleFillLog10(props: TransformedColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillLog10(definedProps(props)));
  return null;
}

export function ScaleFillSqrt(props: TransformedColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillSqrt(definedProps(props)));
  return null;
}

export function ScaleFillDate(props: TemporalColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDate(definedProps(props)));
  return null;
}

export function ScaleFillDatetime(props: TemporalColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDatetime(definedProps(props)));
  return null;
}

export function ScaleFillManual(props: ManualColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillManual(definedProps(props)));
  return null;
}

export function ScaleFillIdentity(props: IdentityColorScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillIdentity(definedProps(props)));
  return null;
}

export function ScaleFillBrewer(props: ColorBrewerScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillBrewer(definedProps(props)));
  return null;
}

export function ScaleFillDistiller(props: ColorDistillerScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillDistiller(definedProps(props)));
  return null;
}

export function ScaleFillFermenter(props: ColorFermenterScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillFermenter(definedProps(props)));
  return null;
}

export function ScaleColorViridisC(props: ViridisScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorViridisC(definedProps(props)));
  return null;
}
export { ScaleColorViridisC as ScaleColourViridisC };

export function ScaleColorViridisD(props: ViridisScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorViridisD(definedProps(props)));
  return null;
}
export { ScaleColorViridisD as ScaleColourViridisD };

export function ScaleColorViridisB(props: ViridisScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleColorViridisB(definedProps(props)));
  return null;
}
export { ScaleColorViridisB as ScaleColourViridisB };

export function ScaleFillViridisC(props: ViridisScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillViridisC(definedProps(props)));
  return null;
}

export function ScaleFillViridisD(props: ViridisScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillViridisD(definedProps(props)));
  return null;
}

export function ScaleFillViridisB(props: ViridisScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleFillViridisB(definedProps(props)));
  return null;
}

export function ScaleSizeContinuous(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeContinuous(definedProps(props)));
  return null;
}

export function ScaleSizeDiscrete(props: DiscreteNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeDiscrete(definedProps(props)));
  return null;
}
export { ScaleSizeDiscrete as ScaleSizeOrdinal };

export function ScaleSizeBinned(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeBinned(definedProps(props)));
  return null;
}

export function ScaleSizeDate(props: TemporalNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeDate(definedProps(props)));
  return null;
}

export function ScaleSizeDatetime(props: TemporalNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeDatetime(definedProps(props)));
  return null;
}

export function ScaleSizeManual(props: ManualNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeManual(definedProps(props)));
  return null;
}

export function ScaleSizeIdentity(props: IdentityNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeIdentity(definedProps(props)));
  return null;
}

export function ScaleLinewidthContinuous(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthContinuous(definedProps(props)));
  return null;
}

export function ScaleLinewidthDiscrete(props: DiscreteNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthDiscrete(definedProps(props)));
  return null;
}
export { ScaleLinewidthDiscrete as ScaleLinewidthOrdinal };

export function ScaleLinewidthBinned(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthBinned(definedProps(props)));
  return null;
}

export function ScaleLinewidthDate(props: TemporalNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthDate(definedProps(props)));
  return null;
}

export function ScaleLinewidthDatetime(props: TemporalNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthDatetime(definedProps(props)));
  return null;
}

export function ScaleLinewidthManual(props: ManualNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthManual(definedProps(props)));
  return null;
}

export function ScaleLinewidthIdentity(props: IdentityNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleLinewidthIdentity(definedProps(props)));
  return null;
}

export function ScaleAlphaContinuous(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaContinuous(definedProps(props)));
  return null;
}

export function ScaleAlphaDiscrete(props: DiscreteNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaDiscrete(definedProps(props)));
  return null;
}
export { ScaleAlphaDiscrete as ScaleAlphaOrdinal };

export function ScaleAlphaBinned(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaBinned(definedProps(props)));
  return null;
}

export function ScaleAlphaDate(props: TemporalNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaDate(definedProps(props)));
  return null;
}

export function ScaleAlphaDatetime(props: TemporalNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaDatetime(definedProps(props)));
  return null;
}

export function ScaleAlphaManual(props: ManualNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaManual(definedProps(props)));
  return null;
}

export function ScaleAlphaIdentity(props: IdentityNumericStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleAlphaIdentity(definedProps(props)));
  return null;
}

export function ScaleSizeArea(props: SizeAreaScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeArea(definedProps(props)));
  return null;
}

export function ScaleSizeBinnedArea(props: SizeAreaScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleSizeBinnedArea(definedProps(props)));
  return null;
}

export function ScaleRadius(props: SequentialStyleScaleOptions): ReactNode {
  usePlotLayerValue("scale", () => scaleRadius(definedProps(props)));
  return null;
}

export function ScaleShapeDiscrete(
  props: DiscreteFiniteStyleScaleOptions<PointShapeName>,
): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeDiscrete(definedProps(props)));
  return null;
}
export { ScaleShapeDiscrete as ScaleShapeOrdinal };

export function ScaleShapeBinned(props: BinnedFiniteStyleScaleOptions<PointShapeName>): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeBinned(definedProps(props)));
  return null;
}

export function ScaleShapeManual(props: ManualFiniteStyleScaleOptions<PointShapeName>): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeManual(definedProps(props)));
  return null;
}

export function ScaleShapeIdentity(
  props: IdentityFiniteStyleScaleOptions<PointShapeName>,
): ReactNode {
  usePlotLayerValue("scale", () => scaleShapeIdentity(definedProps(props)));
  return null;
}

export function ScaleLinetypeDiscrete(
  props: DiscreteFiniteStyleScaleOptions<LinetypeName>,
): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeDiscrete(definedProps(props)));
  return null;
}

export function ScaleLinetypeBinned(props: BinnedFiniteStyleScaleOptions<LinetypeName>): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeBinned(definedProps(props)));
  return null;
}

export function ScaleLinetypeManual(props: ManualFiniteStyleScaleOptions<LinetypeName>): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeManual(definedProps(props)));
  return null;
}

export function ScaleLinetypeIdentity(
  props: IdentityFiniteStyleScaleOptions<LinetypeName>,
): ReactNode {
  usePlotLayerValue("scale", () => scaleLinetypeIdentity(definedProps(props)));
  return null;
}
