/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, QqParams, QqLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerQq } from "@ggsvelte/core";
registerQq();

type ShellProps = QqParams &
  Omit<QqLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomQq(props: ShellProps): ReactNode {
  useGeomLayer("qq", props);
  return null;
}
