/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, PointrangeParams, PointrangeLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerPointrange } from "@ggsvelte/core";
registerPointrange();

type ShellProps = PointrangeParams &
  Omit<PointrangeLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomPointrange(props: ShellProps): ReactNode {
  useGeomLayer("pointrange", props);
  return null;
}
