/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, ErrorbarParams, ErrorbarLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerErrorbar } from "@ggsvelte/core";
registerErrorbar();

type ShellProps = ErrorbarParams &
  Omit<ErrorbarLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomErrorbar(props: ShellProps): ReactNode {
  useGeomLayer("errorbar", props);
  return null;
}
