/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, BoxplotParams, BoxplotLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerBoxplot } from "@ggsvelte/core";
registerBoxplot();

type ShellProps = BoxplotParams &
  Omit<BoxplotLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomBoxplot(props: ShellProps): ReactNode {
  useGeomLayer("boxplot", props);
  return null;
}
