/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, PolygonParams, PolygonLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerPolygon } from "@ggts-sh/core";
registerPolygon();

type ShellProps = PolygonParams &
  Omit<PolygonLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomPolygon(props: ShellProps): ReactNode {
  useGeomLayer("polygon", props);
  return null;
}
