/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, AreaParams, AreaLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = AreaParams &
  Omit<AreaLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomArea(props: ShellProps): ReactNode {
  useGeomLayer("area", props);
  return null;
}
