/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, QqLineParams, QqLineLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerQqLine } from "@ggsvelte/core";
registerQqLine();

type ShellProps = QqLineParams &
  Omit<QqLineLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomQqLine(props: ShellProps): ReactNode {
  useGeomLayer("qq_line", props);
  return null;
}
