/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, FunctionParams, FunctionLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerFunction } from "@ggts-sh/core";
registerFunction();

type ShellProps = FunctionParams &
  Omit<FunctionLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomFunction(props: ShellProps): ReactNode {
  useGeomLayer("function", props);
  return null;
}
