/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, SegmentParams, SegmentLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = SegmentParams &
  Omit<SegmentLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomSegment(props: ShellProps): ReactNode {
  useGeomLayer("segment", props);
  return null;
}
