/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, HexParams, HexLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerHex } from "@ggts-sh/core";
registerHex();

type ShellProps = HexParams &
  Omit<HexLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomHex(props: ShellProps): ReactNode {
  useGeomLayer("hex", props);
  return null;
}
