/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, PointParams, PointLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = PointParams &
  Omit<PointLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomPoint(props: ShellProps): ReactNode {
  useGeomLayer("point", props);
  return null;
}
