/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, CrossbarParams, CrossbarLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerCrossbar } from "@ggsvelte/core";
registerCrossbar();

type ShellProps = CrossbarParams &
  Omit<CrossbarLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomCrossbar(props: ShellProps): ReactNode {
  useGeomLayer("crossbar", props);
  return null;
}
