/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, BarParams, HistogramLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerBin } from "@ggts-sh/core";
registerBin();

type ShellProps = BarParams &
  Omit<HistogramLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomHistogram(props: ShellProps): ReactNode {
  useGeomLayer("histogram", props);
  return null;
}
