/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, BarParams, BarLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = BarParams &
  Omit<BarLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomBar(props: ShellProps): ReactNode {
  useGeomLayer("bar", props);
  return null;
}
