/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, CurveParams, CurveLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerCurve } from "@ggsvelte/core";
registerCurve();

type ShellProps = CurveParams &
  Omit<CurveLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomCurve(props: ShellProps): ReactNode {
  useGeomLayer("curve", props);
  return null;
}
