/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, Density2dParams, Density2dLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerDensity2d } from "@ggts-sh/core";
registerDensity2d();

type ShellProps = Density2dParams &
  Omit<Density2dLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomDensity2d(props: ShellProps): ReactNode {
  useGeomLayer("density_2d", props);
  return null;
}
