/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, SfTextParams, SfTextLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerSfText } from "@ggts-sh/core";
registerSfText();

type ShellProps = SfTextParams &
  Omit<SfTextLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomSfText(props: ShellProps): ReactNode {
  useGeomLayer("sf_text", props);
  return null;
}
