/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, LineParams, FreqpolyLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerBin } from "@ggts-sh/core";
registerBin();

type ShellProps = LineParams &
  Omit<FreqpolyLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomFreqpoly(props: ShellProps): ReactNode {
  useGeomLayer("freqpoly", props);
  return null;
}
