/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, MapParams, MapLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerMap } from "@ggsvelte/core";
registerMap();

type ShellProps = MapParams &
  Omit<MapLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomMap(props: ShellProps): ReactNode {
  useGeomLayer("map", props);
  return null;
}
