/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, ContourParams, ContourLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerContour } from "@ggts-sh/core";
registerContour();

type ShellProps = ContourParams &
  Omit<ContourLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomContour(props: ShellProps): ReactNode {
  useGeomLayer("contour", props);
  return null;
}
