/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, TileParams, TileLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerTile } from "@ggts-sh/core";
registerTile();

type ShellProps = TileParams &
  Omit<TileLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomTile(props: ShellProps): ReactNode {
  useGeomLayer("tile", props);
  return null;
}
