/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, RasterParams, RasterLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerRaster } from "@ggsvelte/core";
registerRaster();

type ShellProps = RasterParams &
  Omit<RasterLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomRaster(props: ShellProps): ReactNode {
  useGeomLayer("raster", props);
  return null;
}
