/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, HlineParams, HlineLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = HlineParams &
  Omit<HlineLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomHline(props: ShellProps): ReactNode {
  useGeomLayer("hline", props);
  return null;
}
