/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, QuantileParams, QuantileLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerQuantile } from "@ggsvelte/core";
registerQuantile();

type ShellProps = QuantileParams &
  Omit<QuantileLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomQuantile(props: ShellProps): ReactNode {
  useGeomLayer("quantile", props);
  return null;
}
