/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, RectParams, RectLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = RectParams &
  Omit<RectLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomRect(props: ShellProps): ReactNode {
  useGeomLayer("rect", props);
  return null;
}
