/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, ColParams, ColLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = ColParams &
  Omit<ColLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomCol(props: ShellProps): ReactNode {
  useGeomLayer("col", props);
  return null;
}
