/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, SmoothParams, SmoothLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerSmooth } from "@ggts-sh/core";
registerSmooth();

type ShellProps = SmoothParams &
  Omit<SmoothLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomSmooth(props: ShellProps): ReactNode {
  useGeomLayer("smooth", props);
  return null;
}
