/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, ViolinParams, ViolinLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerViolin } from "@ggsvelte/core";
registerViolin();

type ShellProps = ViolinParams &
  Omit<ViolinLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomViolin(props: ShellProps): ReactNode {
  useGeomLayer("violin", props);
  return null;
}
