/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, DensityParams, DensityLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerDensity } from "@ggts-sh/core";
registerDensity();

type ShellProps = DensityParams &
  Omit<DensityLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomDensity(props: ShellProps): ReactNode {
  useGeomLayer("density", props);
  return null;
}
