/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, LineParams, LineLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = LineParams &
  Omit<LineLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomLine(props: ShellProps): ReactNode {
  useGeomLayer("line", props);
  return null;
}
