/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, SfParams, SfLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerSf } from "@ggts-sh/core";
registerSf();

type ShellProps = SfParams &
  Omit<SfLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomSf(props: ShellProps): ReactNode {
  useGeomLayer("sf", props);
  return null;
}
