/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, DotplotParams, DotplotLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerDotplot } from "@ggts-sh/core";
registerDotplot();

type ShellProps = DotplotParams &
  Omit<DotplotLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomDotplot(props: ShellProps): ReactNode {
  useGeomLayer("dotplot", props);
  return null;
}
