/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, SfLabelParams, SfLabelLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerSfLabel } from "@ggts-sh/core";
registerSfLabel();

type ShellProps = SfLabelParams &
  Omit<SfLabelLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomSfLabel(props: ShellProps): ReactNode {
  useGeomLayer("sf_label", props);
  return null;
}
