/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, AblineParams, AblineLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerAbline } from "@ggsvelte/core";
registerAbline();

type ShellProps = AblineParams &
  Omit<AblineLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomAbline(props: ShellProps): ReactNode {
  useGeomLayer("abline", props);
  return null;
}
