/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, SpokeParams, SpokeLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerSpoke } from "@ggsvelte/core";
registerSpoke();

type ShellProps = SpokeParams &
  Omit<SpokeLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomSpoke(props: ShellProps): ReactNode {
  useGeomLayer("spoke", props);
  return null;
}
