/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, Bin2dParams, Bin2dLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerBin2d } from "@ggsvelte/core";
registerBin2d();

type ShellProps = Bin2dParams &
  Omit<Bin2dLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomBin2d(props: ShellProps): ReactNode {
  useGeomLayer("bin_2d", props);
  return null;
}
