/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, RibbonParams, RibbonLayerInput } from "@ggsvelte/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = RibbonParams &
  Omit<RibbonLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomRibbon(props: ShellProps): ReactNode {
  useGeomLayer("ribbon", props);
  return null;
}
