/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, PointParams, JitterLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = PointParams &
  Omit<JitterLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
    width?: number;
    height?: number;
    seed?: number;
  };

export function GeomJitter(props: ShellProps): ReactNode {
  const { width, height, seed, positionParams, ...rest } = props;
  useGeomLayer("jitter", {
    ...rest,
    positionParams: {
      ...positionParams,
      ...(typeof width === "number" ? { width } : {}),
      ...(typeof height === "number" ? { height } : {}),
      ...(typeof seed === "number" ? { seed } : {}),
    },
  });
  return null;
}
