/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, TextParams, TextLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
type ShellProps = TextParams &
  Omit<TextLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomText(props: ShellProps): ReactNode {
  useGeomLayer("text", props);
  return null;
}
