/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, RugParams, RugLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerRug } from "@ggts-sh/core";
registerRug();

type ShellProps = RugParams &
  Omit<RugLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomRug(props: ShellProps): ReactNode {
  useGeomLayer("rug", props);
  return null;
}
