/* GENERATED by scripts/gen-react-children.ts — do not edit. */
import type { ReactNode } from "react";
import type { DataInput, LinerangeParams, LinerangeLayerInput } from "@ggts-sh/spec";
import { useGeomLayer } from "../geom-factory.js";
import { registerLinerange } from "@ggts-sh/core";
registerLinerange();

type ShellProps = LinerangeParams &
  Omit<LinerangeLayerInput, "geom" | "params" | "data"> & {
    data?: DataInput | readonly Record<string, unknown>[];
  };

export function GeomLinerange(props: ShellProps): ReactNode {
  useGeomLayer("linerange", props);
  return null;
}
