<!-- GENERATED by scripts/gen-geom-children.ts — do not edit. Run: bun run geom:children:gen -->
<script module lang="ts">
  import { registerSfLabel } from "@ggts-sh/core";

  // Self-registration (#1420): this component's geom batch + default stat
  // frame enter the bundle (and the core registries) only when the
  // component itself is imported. Idempotent.
  registerSfLabel();
</script>

<script lang="ts">
  import type {
    DataInput,
    SfLabelParams,
    SfLabelLayerInput,
  } from "@ggts-sh/spec";

  import { createGeomLayer } from "./factory.svelte.js";

  const props: SfLabelParams &
    Omit<SfLabelLayerInput, "geom" | "params" | "data"> & {
      data?: DataInput | readonly Record<string, unknown>[];
    } = $props();
  createGeomLayer("sf_label", () => props);
</script>
