// Shared pure behavior used by React and Svelte.
export {
  type PresentationChrome,
  type PresentationAnchor,
  type CandidateAnchorKeys,
  EMPHASIS_RING_DENSITY_LIMIT,
  presentationChromeForKind,
  hoverChromeForKind,
  applyEmphasisRingDensityGate,
  sameOrderedPropertyKeys,
  buildPointSelectionEvent,
  uniqueKeysFromRowIndexes,
  nextPointSelectionKeys,
  type CandidateLookup,
  iterateCandidates,
  collectCandidates,
  anchorsFromCandidateKeys,
  type PresentationInspectionFocus,
  type PresentationSeedFacts,
  presentationFocusFromInspection,
  type MergePresentationFocusOptions,
  mergePresentationFocusKeys,
} from "@ggts-sh/core/interaction";
