// Shared pure behavior used by React and Svelte.
export { type PlotRect } from "@ggts-sh/core";
export {
  type PanelBounds,
  panelBoundsFrom,
  type ContinuousZoomDomains,
  clamp,
  frozenZoomDomains,
  normalizedRect,
  HOVER_RING_RADIUS,
  HOVER_CROSSHAIR_GAP_RADIUS,
  type GlyphHoverBox,
  glyphHoverBox,
  crosshairGapForBox,
  type GlyphExtentBatch,
  glyphExtentsFromBatch,
  type CrosshairSegment,
  type CrosshairGapBox,
  CROSSHAIR_BOX_GAP_PAD,
  gappedCrosshairSegmentsWithObstacles,
  gappedCrosshairSegments,
  type GlyphObstacleBatch,
  type GlyphObstaclePanel,
  crosshairGlyphObstacles,
} from "@ggts-sh/core/interaction";
