/**
 * Generate @ggts-sh/react Geom, Scale, and Theme shells from existing manifests.
 */
import { join } from "node:path";

import { defineArtifact, defineArtifactGroup, formatGeneratedSource } from "./artifact.ts";

import { SHELL_MANIFEST as GEOM_MANIFEST } from "./gen-geom-children-manifest.ts";
import { SHELL_MANIFEST as SCALE_MANIFEST } from "./gen-scale-children-manifest.ts";

const GEOM_DIR = "packages/react/src/geoms";
const SCALE_OUT = "packages/react/src/scales.tsx";
const THEME_OUT = "packages/react/src/themes.tsx";

function geomShellBody(spec: (typeof GEOM_MANIFEST)[number]): string[] {
  if (spec.kind === "jitter") {
    return [
      `export function ${spec.component}(props: ShellProps): ReactNode {`,
      `  const { width, height, seed, positionParams, ...rest } = props;`,
      `  useGeomLayer("jitter", {`,
      `    ...rest,`,
      `    positionParams: {`,
      `      ...positionParams,`,
      `      ...(typeof width === "number" ? { width } : {}),`,
      `      ...(typeof height === "number" ? { height } : {}),`,
      `      ...(typeof seed === "number" ? { seed } : {}),`,
      `    },`,
      `  });`,
      `  return null;`,
      `}`,
    ];
  }
  return [
    `export function ${spec.component}(props: ShellProps): ReactNode {`,
    `  useGeomLayer("${spec.geom}", props);`,
    `  return null;`,
    `}`,
  ];
}

function geomFiles(): [string, string][] {
  const files: [string, string][] = [];
  const index: string[] = [`/* GENERATED by scripts/gen-react-children.ts — do not edit. */`, ``];
  for (const spec of GEOM_MANIFEST) {
    const register =
      spec.registration === undefined
        ? []
        : [`import { ${spec.registration} } from "@ggts-sh/core";`, `${spec.registration}();`, ``];
    const source = [
      `/* GENERATED by scripts/gen-react-children.ts — do not edit. */`,
      `import type { ReactNode } from "react";`,
      `import type { DataInput, ${spec.paramsType}, ${spec.layerInput} } from "@ggts-sh/spec";`,
      `import { useGeomLayer } from "../geom-factory.js";`,
      ...register,
      `type ShellProps = ${spec.paramsType} & Omit<${spec.layerInput}, "geom" | "params" | "data"> & {`,
      `  data?: DataInput | readonly Record<string, unknown>[];`,
      ...(spec.kind === "jitter"
        ? [`  width?: number;`, `  height?: number;`, `  seed?: number;`]
        : []),
      `};`,
      ``,
      ...geomShellBody(spec),
      ``,
    ].join("\n");
    files.push([`${GEOM_DIR}/${spec.component}.tsx`, source]);
    index.push(`export { ${spec.component} } from "./${spec.component}.js";`);
  }
  index.push(``);
  files.push([`${GEOM_DIR}/index.ts`, index.join("\n")]);
  return files;
}

function scaleFile(): string {
  const helpers = SCALE_MANIFEST.map((s) => s.helper);
  const types = [...new Set(SCALE_MANIFEST.flatMap((s) => s.typeImports))].toSorted();
  const lines = [
    `/* GENERATED by scripts/gen-react-children.ts — do not edit. */`,
    `import "@ggts-sh/core/temporal";`,
    `import type { ReactNode } from "react";`,
    `import type { ${types.join(", ")} } from "@ggts-sh/spec";`,
    `import {`,
    ...helpers.map((h, i) => `  ${h}${i < helpers.length - 1 ? "," : ""}`),
    `} from "@ggts-sh/spec";`,
    `import { definedProps } from "./defined-props.js";`,
    `import { usePlotLayerValue } from "./geom-factory.js";`,
    ``,
  ];
  for (const spec of SCALE_MANIFEST) {
    lines.push(
      `export function ${spec.component}(props: ${spec.optionsType}): ReactNode {`,
      `  usePlotLayerValue("scale", () => ${spec.helper}(definedProps(props)));`,
      `  return null;`,
      `}`,
    );
    if (spec.aliases) {
      for (const alias of spec.aliases) {
        lines.push(`export { ${spec.component} as ${alias} };`);
      }
    }
    lines.push(``);
  }
  return lines.join("\n");
}

const THEME_COMPONENTS: [string, string][] = [
  ["default", "ThemeDefault"],
  ["light", "ThemeLight"],
  ["dark", "ThemeDark"],
  ["minimal", "ThemeMinimal"],
  ["ggplot2", "ThemeGgplot2"],
  ["classic", "ThemeClassic"],
  ["bw", "ThemeBw"],
  ["hrbr", "ThemeHrbr"],
  ["few", "ThemeFew"],
  ["clean", "ThemeClean"],
  ["fivethirtyeight", "ThemeFivethirtyeight"],
  ["economist", "ThemeEconomist"],
  ["tufte", "ThemeTufte"],
  ["linedraw", "ThemeLinedraw"],
  ["void", "ThemeVoid"],
  ["stata", "ThemeStata"],
  ["stata_s1color", "ThemeStatas1color"],
  ["solarized", "ThemeSolarized"],
  ["solarizeddark", "ThemeSolarizeddark"],
  ["economist_white", "ThemeEconomistwhite"],
  ["solarized_2", "ThemeSolarized2"],
  ["solarized_2dark", "ThemeSolarized2dark"],
  ["wsj", "ThemeWsj"],
  ["hc", "ThemeHc"],
  ["hcdark", "ThemeHcdark"],
  ["pander", "ThemePander"],
  ["base", "ThemeBase"],
  ["igray", "ThemeIgray"],
  ["map", "ThemeMap"],
  ["solid", "ThemeSolid"],
  ["grey", "ThemeGrey"],
  ["gray", "ThemeGray"],
];

function themeFile(): string {
  const lines = [
    `/* GENERATED by scripts/gen-react-children.ts — do not edit. */`,
    `import type { ReactNode } from "react";`,
    `import type { ThemeName, ThemeSpec } from "@ggts-sh/spec";`,
    `import { definedProps } from "./defined-props.js";`,
    `import { usePlotLayerValue } from "./geom-factory.js";`,
    ``,
    `type RoleProps = Partial<ThemeSpec>;`,
    ``,
    `function useNamedTheme(name: ThemeName, props: RoleProps): void {`,
    `  usePlotLayerValue("theme", () => {`,
    `    const roles = definedProps(props);`,
    `    return Object.keys(roles).length === 0 ? name : { name, ...roles };`,
    `  });`,
    `}`,
    ``,
  ];
  for (const [name, component] of THEME_COMPONENTS) {
    lines.push(
      `export function ${component}(props: RoleProps = {}): ReactNode {`,
      `  useNamedTheme("${name}", props);`,
      `  return null;`,
      `}`,
      ``,
    );
  }
  lines.push(
    `export function ThemeTest(props: RoleProps = {}): ReactNode {`,
    `  useNamedTheme("test", props);`,
    `  return null;`,
    `}`,
    ``,
  );
  return lines.join("\n");
}

export function reactChildrenGroup(repoRoot: string) {
  const files: [string, string][] = [
    ...geomFiles(),
    [SCALE_OUT, scaleFile()],
    [THEME_OUT, themeFile()],
  ];
  return defineArtifactGroup({
    regenerateWith: "react:children:gen",
    members: files.map(([path, source]) =>
      defineArtifact({
        path: join(repoRoot, path),
        label: path,
        regenerateWith: "react:children:gen",
        build: () => formatGeneratedSource(path, source),
      }),
    ),
  });
}

if (import.meta.main) {
  await reactChildrenGroup(join(import.meta.dir, "..")).cli();
}
